django_kakeibo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('kakeibo/', include('kakeibo.urls'))
]

kakeibo/urls.py
from django.urls import path
from .views import about, BalanceList, DetailBalance, balance_edit, balance_delete

app_name = 'kakeibo'
urlpatterns = [
    path('about/', view = about, name='about'),
    path('list/', view = BalanceList.as_view(), name='balance_list'),
    path('detail/<int:pk>/', view = DetailBalance.as_view(), name='balance_detail'),
    path('add/', view = balance_edit, name='balance_add'),
    path('edit/<int:balance_id>/', view = balance_edit, name='balance_edit'),
    path('delete/<int:balance_id>/', view = balance_delete, name='balance_delete')
]

kakeibo/models.py
# Create your models here.
from django.db import models
import datetime

# Create your models here.
class Balance(models.Model):
  ITEM_CATEGORY_CHOICES = [
    ('給与所得', '給与所得'),
    ('食費', '食費'),
    ('水道代', '水道代'),
    ('ガス代', 'ガス代'),
    ('電気代', '電気代'),
    ('携帯代', '携帯代'),
    ('ガチャ課金', 'ガチャ課金'),
    ('通信費', '通信費'),
    ('交際費', '交際費'),
    ('交通費', '交通費'),
    ('家賃', '家賃'),
    ('その他', 'その他')
  ]

  BALANCE_CHOICES = [
    ('収入', '収入'),
    ('支出', '支出')
  ]

  # 項目名
  item_name = models.CharField(verbose_name='名前', max_length=100)

  # 金額
  amount = models.IntegerField(default = 0)

  # 日時
  registered_date = models.DateField(verbose_name='日時', null = True)

  # カテゴリ
  category = models.CharField(max_length=100, verbose_name='カテゴリ', choices=ITEM_CATEGORY_CHOICES)

  # 収入化支出か
  balance_type = models.CharField(max_length=20, verbose_name='収支タイプ' ,choices=BALANCE_CHOICES)

  def __str__(self):
    return self.item_name

login/models.py
from django.db import models

# Create your models here.

kakeibo/forms.py
from django import forms
from .models import Balance

'''
ITEM_CATEGORY_CHOICES = [
  ('給与所得', '給与所得'),
  ('食費', '食費'),
  ('水道代', '水道代'),
  ('ガス代', 'ガス代'),
  ('電気代', '電気代'),
  ('携帯代', '携帯代'),
  ('ガチャ課金', 'ガチャ課金'),
  ('通信費', '通信費'),
  ('交際費', '交際費'),
  ('交通費', '交通費'),
  ('家賃', '家賃'),
  ('その他', 'その他')
]

BALANCE_CHOICES = [
  ('収入', '収入'),
  ('支出', '支出')
]


class BalanceForm(forms.Form):
  item_name = forms.CharField(
    label = "タイトル",
    max_length = 100,
    required=True
  )

  amount = forms.IntegerField(
    label = '金額',
    required = True
  )

  registered_date = forms.DateField(
    label="日時",
    widget=forms.DateInput(attrs={'type': 'date'}),
    input_formats=['%y-%m-%d'],
    required= False
  )

  category = forms.ChoiceField(
    label= 'カテゴリ',
    widget=forms.Select,
    choices = ITEM_CATEGORY_CHOICES,
    required=True
  )

  balance_type = forms.ChoiceField(
    label = '収支タイプ',
    widget=forms.Select,
    choices = BALANCE_CHOICES,
    required = True
  )
  '''


class BalanceForm(forms.ModelForm):
    
    class Meta:
      model = Balance
      fields = '__all__'

kakeibo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View
from .models import Balance
from .forms import BalanceForm
from django.urls import reverse_lazy
import logging
from django.conf import settings
import os

def about(request):
  return render(request, template_name="about.html")

class BalanceList(ListView):
  context_object_name = 'balance'
  template_name = 'balance_list.html'
  model = Balance

class DetailBalance(DetailView):
  context_object_name = 'balance'
  template_name = 'balance_detail.html'
  model = Balance

  pagenate_by = 10

def balance_edit(request, balance_id=None):
  if balance_id:
    balance = get_object_or_404(Balance, pk = balance_id)
  else:
    balance = Balance()

  if request.method == 'POST':
    form = BalanceForm(request.POST, instance = balance)

    if form.is_valid():
      balance = form.save()
      return redirect('kakeibo:balance_list')

  else:
    form = BalanceForm(instance=balance)

  return render(request, 'balance_edit.html', dict(form=form, balance_id=balance_id))

def balance_delete(request, balance_id):
  balance = get_object_or_404(Balance, pk = balance_id)

  balance.delete()
  return redirect('kakeibo:balance_list')

login/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% extends 'base.html' %}

{% block page_title %}
  <title>About - Kakeibo</title>
{% endblock page_title%}

templates/balance_detail.html
{% extends 'base.html'%}

{% block content %}
<p>{{ balance.item_name }}</p>
<p>{{ balance.amount }}</p>
<p>{{ balance.registered_date }}</p>
<p>{{ balance.category }}</p>
<p>{{ balance.balance_type }}</p>

<a href="{% url 'kakeibo:balance_edit' balance_id=balance.pk %}"
  class="btn btn-secondary"
>
  編集
</a>
<a href="{% url 'kakeibo:balance_delete' balance_id=balance.pk %}"
  class = "btn btn-danger"
>
  削除
</a>
<a href="{% url 'kakeibo:balance_list' %}">戻る</a>
{% endblock content %}

templates/balance_edit.html
{% extends 'base.html'%}
{% load static %}

{% block extracss %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/balance_edit.css' %}" />
{% endblock extracss %}
{% block content %}

  <form method="POST" class="app-form" action="">
  <table class = "form-table">
    {% csrf_token %}

    <tbody>
      <div>
        <label for="id_item_name">タイトル</label>
        <div>
          <input type="text" name="item_name" 
            maxlength="100" required="" id="id_item_name"
            class = "form-control" placeholder="Title"
          >
        </div>
      </div>
      <div>
        <label for="id_amount">金額</label>
        <div>
          <input type="number" name="amount" 
            value="0" required="" id="id_amount"
            class = "form-control" placeholder="Amount"
          >
        </div>
      </div>
      <div>
        <label for="id_registered_date">日時</label>
        <div>
          <input type="text" name="registered_date" 
            required="" id="id_registered_date"
            class = "form-control" placeholder="YYYY-MM-DD"
          >
        </div>
      </div>
      <div>
        <label for="id_category">カテゴリ</th>
        <select name="category" required="" id="id_category"
          class="custom-select"
        >
          <option selected disabled value="">---------</option>
          <option value="給与所得">給与所得</option>
          <option value="食費">食費</option>
          <option value="水道代">水道代</option>
          <option value="ガス代">ガス代</option>
          <option value="電気代">電気代</option>
          <option value="携帯代">携帯代</option>
          <option value="ガチャ課金">ガチャ課金</option>
          <option value="通信費">通信費</option>
          <option value="交際費">交際費</option>
          <option value="交通費">交通費</option>
          <option value="家賃">家賃</option>
          <option value="その他">その他</option>
        </select>
      </div>
      <div>
        <label for="id_balance_type">収支タイプ</label>
        <select name="balance_type" required="" id="id_balance_type"
          class = "custom-select"
        >
          <option value="" disabled selected >---------</option>
          <option value="収入">収入</option>
          <option value="支出">支出</option>
        </select>
      </div>
    </tbody>  

  </table>
    <button type="submit" class="btn btn-primary">
      追加
    </button>
  </form>
<a href="{% url 'kakeibo:balance_list' %}">戻る</a>

{% endblock content %}

templates/balance_list.html
{% extends 'base.html' %}
{% load static %}

{% block extracss %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/balance_list.css' %}" />
{% endblock extracss %}

{% block content %}
<div class="table-responsive">
<table class= "balance-table table table-hover">
  <thead>
    <tr>
      <th>項目名</th>
      <th>金額</th>
      <th>日時</th>
      <th>カテゴリー</th>
      <th>収入/支出</th>
    </tr>
  </thead>
  <tbody>
    {% for item in balance %}
      <tr>
        <td>
         <a href="{% url 'kakeibo:balance_detail' item.pk %}"> {{ item.item_name }} </a>
        </td>
        <td>
          {{ item.amount }}
        </td>
        <td>
          {{ item.registered_date }}
        </td>
        <td>
          {{ item.category }}
        </td>
        <td>
          {{ item.balance_type }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<div>
<p>
  <a href="{% url 'kakeibo:balance_add' %}"
    class = 'btn btn-primary'
  >
    新規追加
  </a>
</p>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block page_title %}
    <title>家計簿</title>
  {% endblock page_title %}
  {% block extracss %}
  {% endblock extracss %}
</head>
<body>
  <header class="app-header">
    <h1>家計簿</h1>  
  </header>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

  <footer class="app-footer">
    <p>This Application is created with Django.</p>
  </footer>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  {% block extrajs %}
  {% endblock extrajs %}

</body>
</html>

templates/pagenation.html
<nav aria-label="pagenation">
	<ul class="pagination">

		{% if page_obj.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="前へ">
					<span aria-hidden="true">&laquo;</span>
				</a>
			</li>
		{% endif %}

		{% for page_num in page_obj.paginator.page_range %} 
			{% if page_num == page_obj.number %}
				<li class="page-item active">
					<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
				</li>
			{% else %}
				<li class="page-item">
					<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
				</li>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="次へ">
					<span aria-hidden="true">&raquo;</span>
				</a>
			</li>
		{% endif %}

	</ul>
</nav>